version: '3'
services:
  elasticsearch:
    build: .
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:latest
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
